### ISSUE TITLE
Unable to connect internal valkey db (subchart)

### ISSUE THREAD

**Issue by daftu** [small-hack/peertube-helm-chart#18]
When using included valkey subchart, Peertube is trying to use "redis" hostname to connect to, instead of connecting to valkey svc (don't know which one is valid but one of "peertube-valkey-headless"  or "peertube-valkey-primary" services should be used)

Config:
```
valkey:
  # -- enable the valkey (alternative to redis) subchart
  enabled: true
  auth:
    # -- you must set a password; the password generated by the valkey chart will be
    # rotated on each upgrade:
    password: ""
    # -- you can also specify the name of an existing Secret
    existingSecret: "peertube-secret"
    # -- key of password in existing secret
    existingSecretPasswordKey: "valkeySecret"
```
Peertube log:
```
[peertube.example.com:443] 2025-04-18 14:07:50.958 error: Reconnecting to redis in 2000.
[peertube.example.com:443] 2025-04-18 14:07:52.967 error: Redis failed to connect {
  "err": {
    "stack": "Error: getaddrinfo ENOTFOUND redis\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)",
    "message": "getaddrinfo ENOTFOUND redis",
    "errno": -3008,
    "code": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "redis"
  }
}
[peertube.example.com:443] 2025-04-18 14:07:52.968 error: Connection to redis has closed.
[peertube.example.com:443] 2025-04-18 14:07:52.968 error: Reconnecting to redis in 2000.
[peertube.example.com:443] 2025-04-18 14:07:54.977 error: Redis failed to connect {
  "err": {
    "stack": "Error: getaddrinfo ENOTFOUND redis\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)",
    "message": "getaddrinfo ENOTFOUND redis",
    "errno": -3008,
    "code": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "redis"
  }
}
[peertube.example.com:443] 2025-04-18 14:07:54.977 error: Connection to redis has closed.
[peertube.example.com:443] 2025-04-18 14:07:54.978 error: Reconnecting to redis in 2000.
[peertube.example.com:443] 2025-04-18 14:07:55.147 debug: Serving en-US HTML language
[peertube.example.com:443] 2025-04-18 14:07:55.151 info: 10.111.1.23 - - [18/Apr/2025:14:07:55 +0000] "GET / HTTP/1.1" 200 19891 "-" "kube-probe/1.32"
[peertube.example.com:443] 2025-04-18 14:07:56.989 error: Redis failed to connect {
  "err": {
    "stack": "Error: getaddrinfo ENOTFOUND redis\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)",
    "message": "getaddrinfo ENOTFOUND redis",
    "errno": -3008,
    "code": "ENOTFOUND",
    "syscall": "getaddrinfo",
    "hostname": "redis"
  }
}
[peertube.example.com:443] 2025-04-18 14:07:56.990 error: Connection to redis has closed.
[peertube.example.com:443] 2025-04-18 14:07:56.990 error: Reconnecting to redis in 2000.
```
